import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import UserLayout from '../components/user/UserLayout'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Card from '../components/Card'

export default function Home() {
  return (
    <>
    <UserLayout>
    <Head>
        <title>Profil Dosen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Halo selamat datang di website profil dosen stikom PGRI BANYUWANGI
        <Card/>
        
      </main>
      <footer>
      
      </footer>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></Script>

    </UserLayout>
    </>
  )
}
